// src/components/Header.tsx
import { Box, Flex } from "@atlaskit/primitives";
import React from "react";
import FPSCounter from "./FPSCounter";
import Button from "@atlaskit/button/new";

interface HeaderProps {
  scrollMode: "window" | "list";
  setScrollMode: (value: "window" | "list") => void;
  showImage: boolean;
  setShowImage: (value: boolean) => void;
}

const Header: React.FC<HeaderProps> = ({
  scrollMode,
  setScrollMode,
  showImage,
  setShowImage,
}) => {
  const toggleScrollMode = () => {
    setScrollMode(scrollMode === "window" ? "list" : "window");
  };

  const toggleShowImage = () => {
    setShowImage(!showImage);
  };

  return (
    <Box as="header" padding="space.200" backgroundColor="elevation.surface">
      <Flex justifyContent="space-between" alignItems="center">
        <FPSCounter />
        <Flex gap="space.200">
          <Button onClick={toggleScrollMode} appearance="primary">
            Scroll: {scrollMode === "window" ? "Window" : "List"}
          </Button>
          <Button appearance="primary" onClick={toggleShowImage}>
            Mode: {showImage ? "Image" : "Text"}
          </Button>
          <a
            href="https://github.com/hungify/pragmatic-custom-preview"
            target="_blank"
            style={{ display: "flex", alignItems: "center" }}
          >
            <img
              src="/icons/github.svg"
              alt="GitHub"
              style={{ width: 28, height: 28 }}
            />
          </a>
        </Flex>
      </Flex>
    </Box>
  );
};

export default Header;

// src/components/Header.vue
<template>
  <header class="header">
    <div class="actions">
      <FPSCounter />
      <div class="scroll-controls">
        <button
          class="control-btn"
          :class="{ active: scrollMode === 'window' }"
          @click="toggleScrollMode"
        >
          Scroll: {{ scrollMode === "window" ? "Window" : "List" }}
        </button>
        <button
          class="control-btn"
          :class="{ active: showImage }"
          @click="toggleShowImage"
        >
          Mode: {{ showImage ? "Image" : "Text" }}
        </button>
        <a
          href="https://github.com/hungify/pragmatic-custom-preview"
          target="_blank"
          class="github-link"
        >
          <img src="/icons/github.svg" alt="GitHub" />
        </a>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import FPSCounter from "./FPSCounter.vue";

defineProps<{
  scrollMode: "window" | "list";
  showImage: boolean;
}>();
defineEmits<{
  "update:scrollMode": (value: "window" | "list") => void;
  "update:showImage": (value: boolean) => void;
}>();

const scrollMode = defineModel("scrollMode", {
  type: String,
  default: "window",
});

const showImage = defineModel("showImage", {
  type: Boolean,
  default: true,
});

const toggleScrollMode = () => {
  scrollMode.value = scrollMode.value === "window" ? "list" : "window";
};

const toggleShowImage = () => {
  showImage.value = !showImage.value;
};
</script>

<style scoped>
.header {
  position: sticky;
  top: 0;
  z-index: 10;
  background: white;
  padding: 12px;
  border-bottom: 1px solid #eee;
}

.actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 12px;
}

.scroll-controls {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 16px;
}

.control-btn {
  padding: 8px 16px;
  border: 1px solid #ddd;
  background: #6b4ce6;
  color: #fff;
  border-color: #6b4ce6;
  border-radius: 4px;
  cursor: pointer;
  transition: all 0.2s;
}

.github-link img {
  width: 28px;
  height: 28px;
}
</style>
