// src/App.tsx
import { Box, Text, xcss } from "@atlaskit/primitives";
import { useState } from "react";
import { getColumns } from "./utils";
import ColumnCustom from "./components/custom-preview/Column";
import Header from "./components/Header";
import ColumnNative from "./components/native-preview/Column";

const columnContainerStyles = xcss({
  width: "100%",
});

const boardStyles = xcss({
  display: "flex",
  gap: "space.200",
  borderWidth: "border.width",
  borderColor: "color.border.accent.purple",
  borderStyle: "solid",
  borderRadius: "border.radius",
  padding: "space.200",
  backgroundColor: "elevation.surface.sunken",
});

const nativeSymbol = Symbol("native");
const customSymbol = Symbol("custom");

const list = [
  {
    instanceId: nativeSymbol,
    title: "Native Preview",
  },
  {
    instanceId: customSymbol,
    title: "Custom Preview",
  },
];

function App() {
  const [nativeColumns, setNativeColumns] = useState(() =>
    getColumns({ count: 50, prefix: "Native" })
  );
  const [customColumns, setCustomColumns] = useState(() =>
    getColumns({ count: 50, prefix: "Custom" })
  );

  const [scrollMode, setScrollMode] = useState<"window" | "list">("window");
  const [showImage, setShowImage] = useState(false);

  return (
    <>
      <Header
        scrollMode={scrollMode}
        setScrollMode={setScrollMode}
        showImage={showImage}
        setShowImage={setShowImage}
      />
      <Box xcss={boardStyles}>
        {list.map((item) => (
          <Box key={item.instanceId.toString()} xcss={columnContainerStyles}>
            <Text size="large" as="strong">
              {item.title}
            </Text>
            {item.instanceId === customSymbol ? (
              <ColumnCustom
                columns={customColumns}
                instanceId={item.instanceId}
                scrollMode={scrollMode}
                showImage={showImage}
                setColumns={setCustomColumns}
              />
            ) : (
              <ColumnNative
                columns={nativeColumns}
                instanceId={item.instanceId}
                scrollMode={scrollMode}
                showImage={showImage}
                setColumns={setNativeColumns}
              />
            )}
          </Box>
        ))}
      </Box>
    </>
  );
}

export default App;

// src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import ListCustom from "./components/custom-preview/ListCustom.vue";
import ListNative from "./components/native-preview/ListNative.vue";
import { getColumns } from "./utils";
import Header from "./components/Header.vue";

const nativeSymbol = Symbol("native");
const customSymbol = Symbol("custom");

const list = [
  {
    items: ref(getColumns({ count: 150, prefix: "Native" })),
    instanceId: nativeSymbol,
    title: "Native Preview",
  },
  {
    items: ref(getColumns({ count: 150, prefix: "Custom" })),
    instanceId: customSymbol,
    title: "Custom Preview",
  },
];

const scrollMode = ref<"window" | "list">("window");
const showImage = ref(false);
</script>

<template>
  <div>
    <Header v-model:scrollMode="scrollMode" v-model:showImage="showImage" />
    <div class="grid" :class="{ 'list-scroll': scrollMode === 'list' }">
      <div class="custom-preview" v-for="item in list" :key="item.instanceId">
        <h4 class="title">{{ item.title }}</h4>
        <Component
          :is="item.instanceId === customSymbol ? ListCustom : ListNative"
          v-model:items="item.items.value"
          :instanceId="item.instanceId"
          :scrollMode="scrollMode"
          :showImage="showImage"
        />
      </div>
    </div>
  </div>
</template>

<style scoped>
.grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
  padding: 8px;
}

.custom-preview {
  background-color: #f5f5f5;
  padding: 10px;
  border-radius: 5px;
}

.native-preview {
  background-color: #f5f5f5;
  padding: 10px;
  border-radius: 5px;
}

.title {
  color: #333;
  margin: 0 0 10px;
}
</style>
